import { Additive } from '../../shared/interfaces/types';

export const COMMON_ADDITIVES: Additive[] = [
  { code: "E100", name: "Curcumina", category: "colorante" },
  { code: "E101", name: "Riboflavina", category: "colorante" },
  { code: "E110", name: "Giallo arancio S", category: "colorante" },
  { code: "E120", name: "Cocciniglia", category: "colorante" },
  { code: "E200", name: "Acido sorbico", category: "conservante" },
  { code: "E202", name: "Sorbato di potassio", category: "conservante" },
  { code: "E211", name: "Benzoato di sodio", category: "conservante" },
  { code: "E220", name: "Anidride solforosa", category: "conservante" },
  { code: "E249", name: "Nitrito di potassio", category: "conservante" },
  { code: "E250", name: "Nitrito di sodio", category: "conservante" },
  { code: "E251", name: "Nitrato di sodio", category: "conservante" },
  { code: "E260", name: "Acido acetico", category: "regolatore di acidità" },
  { code: "E300", name: "Acido ascorbico (Vitamina C)", category: "antiossidante" },
  { code: "E322", name: "Lecitine", category: "emulsionante" },
  { code: "E330", name: "Acido citrico", category: "regolatore di acidità" },
  { code: "E331", name: "Citrati di sodio", category: "regolatore di acidità" },
  { code: "E407", name: "Carragenina", category: "addensante" },
  { code: "E410", name: "Farina di semi di carrube", category: "addensante" },
  { code: "E412", name: "Gomma di guar", category: "addensante" },
  { code: "E415", name: "Gomma xantano", category: "addensante" },
  { code: "E420", name: "Sorbitolo", category: "edulcorante" },
  { code: "E422", name: "Glicerolo", category: "umidificante" },
  { code: "E440", name: "Pectine", category: "gelificante" },
  { code: "E450", name: "Difosfati", category: "agente lievitante" },
  { code: "E471", name: "Mono- e digliceridi degli acidi grassi", category: "emulsionante" },
  { code: "E472", name: "Esteri degli acidi grassi", category: "emulsionante" },
  { code: "E950", name: "Acesulfame K", category: "edulcorante" },
  { code: "E951", name: "Aspartame", category: "edulcorante" },
  { code: "E952", name: "Acido ciclammico", category: "edulcorante" },
  { code: "E954", name: "Saccarina", category: "edulcorante" },
  { code: "E955", name: "Sucralosio", category: "edulcorante" }
];
